export const UNLOCKS = {
  armorUnlocks : {
    BaseballCap:{
      id: "baseballcap",
      title: "Baseball Cap",
      key: "bas",
      asset: require("../assets/AppAssets/Unlocks/Reveals/BaseballCap.png"),
    },
    Beanie: {
      id: "beanie",
      title: "Beanie" ,
      key: "bea",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Beanie.png"),
    },
    Beret: {
      id: "beret",
      title: "Beret" ,
      key: "ber",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Beret.png"),
    },
    Bucket:{
      id: "bucket",
      title: "Bucket" ,
      key: "buc",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Bucket.png"),
    },
    BucketHat:{
      id: "buckethat",
      title: "Bucket Hat",
      key: "buh",
      asset: require("../assets/AppAssets/Unlocks/Reveals/BucketHat.png"), 
    },
    CatEars:{
      id: "catears",
      title: "Cat Ears",
      key: "cat",
      asset: require("../assets/AppAssets/Unlocks/Reveals/CatEars.png"),
    },
    Headphones: {
      id: "headphones" ,
      title: "Headphones",
      key: "hea",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Headphones.png"),
    },
    Propeller:{
      id: "propeller" ,
      title: "Propeller",
      key: "pro",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Propeller.png"),
    },
    Leaf: {
      id: "leaf",
      title: "Leaf" ,
      key: "lea",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Leaf.png"),
    },
    Pan: {
      id: "pan" ,
      title: "Pan",
      key: "pan",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Pan.png"),
    },
    PaperHat:{
      id: "paperhat",
      title: "Paper Hat" ,
      key: "pap",
      asset: require("../assets/AppAssets/Unlocks/Reveals/PaperHat.png"),
    },
    Party:{
      id: "party" ,
      title: "Party",
      key: "par",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Party.png"),
    },
    TopHat:{
      id: "tophat" ,
      title: "Top Hat",
      key: "top",
      asset: require("../assets/AppAssets/Unlocks/Reveals/TopHat.png"),
    }, 
    Raccoon:{
      id: "raccoon",
      title: "Raccoon" ,
      key: "rac",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Raccoon.png"),
    },
    RussianHat:{
      id: "russianhat",
      title: "Russian Hat",
      key: "rus",
      asset: require("../assets/AppAssets/Unlocks/Reveals/RussianHat.png"),
    },
  },
  unlocks: {
    Autumn: require("../assets/AppAssets/Unlocks/Reveals/Autumn.png"),
    Cherry: require("../assets/AppAssets/Unlocks/Reveals/Cherry.png"),
    Winter: require("../assets/AppAssets/Unlocks/Reveals/Winter.png"),
    Starry: require("../assets/AppAssets/Unlocks/Reveals/Starry.png"),
    Sunset: require("../assets/AppAssets/Unlocks/Reveals/Sunset.png"),
    B_Dots: require("../assets/AppAssets/Unlocks/Reveals/B.Dots.png"),
    B_Flowers: require("../assets/AppAssets/Unlocks/Reveals/B.Flowers.png"),
    B_Hearts: require("../assets/AppAssets/Unlocks/Reveals/B.Hearts.png"),
    B_Stars: require("../assets/AppAssets/Unlocks/Reveals/B.Stars.png"),
    B_Stripes: require("../assets/AppAssets/Unlocks/Reveals/B.Stripes.png"),
    B_Waves: require("../assets/AppAssets/Unlocks/Reveals/B.Waves.png"),
    Bl_Dots: require("../assets/AppAssets/Unlocks/Reveals/Bl.Dots.png"),
    Bl_Flowers: require("../assets/AppAssets/Unlocks/Reveals/Bl.Flowers.png"),
    Bl_Hearts: require("../assets/AppAssets/Unlocks/Reveals/Bl.Hearts.png"),
    Bl_Stars: require("../assets/AppAssets/Unlocks/Reveals/Bl.Stars.png"),
    Bl_Stripes: require("../assets/AppAssets/Unlocks/Reveals/Bl.Stripes.png"),
    Bl_Waves: require("../assets/AppAssets/Unlocks/Reveals/Bl.Waves.png"),
    Br_Dots: require("../assets/AppAssets/Unlocks/Reveals/Br.Dots.png"),
    Br_Flowers: require("../assets/AppAssets/Unlocks/Reveals/Br.Flowers.png"),
    Br_Hearts: require("../assets/AppAssets/Unlocks/Reveals/Br.Hearts.png"),
    Br_Stars: require("../assets/AppAssets/Unlocks/Reveals/Br.Stars.png"),
    Br_Stripes: require("../assets/AppAssets/Unlocks/Reveals/Br.Stripes.png"),
    Br_Waves: require("../assets/AppAssets/Unlocks/Reveals/Br.Waves.png"),
    Cloudy_Rain: require("../assets/AppAssets/Unlocks/Reveals/Cloudy.Rain.png"),
    Cloudy_Sunny: require("../assets/AppAssets/Unlocks/Reveals/Cloudy.Sunny.png"),
    G_Dots: require("../assets/AppAssets/Unlocks/Reveals/G.Dots.png"),
    G_Flowers: require("../assets/AppAssets/Unlocks/Reveals/G.Flowers.png"),
    G_Hearts: require("../assets/AppAssets/Unlocks/Reveals/G.Hearts.png"),
    G_Stars: require("../assets/AppAssets/Unlocks/Reveals/G.Stars.png"),
    G_Stripes: require("../assets/AppAssets/Unlocks/Reveals/G.Stripes.png"),
    G_Waves: require("../assets/AppAssets/Unlocks/Reveals/G.Waves.png"),
    Gr_Dots: require("../assets/AppAssets/Unlocks/Reveals/Gr.Dots.png"),
    Gr_Flowers: require("../assets/AppAssets/Unlocks/Reveals/Gr.Flowers.png"),
    Gr_Hearts: require("../assets/AppAssets/Unlocks/Reveals/Gr.Hearts.png"),
    Gr_Stars: require("../assets/AppAssets/Unlocks/Reveals/Gr.Stars.png"),
    Gr_Stripes: require("../assets/AppAssets/Unlocks/Reveals/Gr.Stripes.png"),
    Gr_Waves: require("../assets/AppAssets/Unlocks/Reveals/Gr.Waves.png"),
    L_Dots: require("../assets/AppAssets/Unlocks/Reveals/L.Dots.png"),
    L_Flowers: require("../assets/AppAssets/Unlocks/Reveals/L.Flowers.png"),
    L_Hearts: require("../assets/AppAssets/Unlocks/Reveals/L.Hearts.png"),
    L_Stars: require("../assets/AppAssets/Unlocks/Reveals/L.Stars.png"),
    L_Stripes: require("../assets/AppAssets/Unlocks/Reveals/L.Stripes.png"),
    L_Waves: require("../assets/AppAssets/Unlocks/Reveals/L.Waves.png"),
    O_Dots: require("../assets/AppAssets/Unlocks/Reveals/O.Dots.png"),
    O_Flowers: require("../assets/AppAssets/Unlocks/Reveals/O.Flowers.png"),
    O_Hearts: require("../assets/AppAssets/Unlocks/Reveals/O.Hearts.png"),
    O_Stars: require("../assets/AppAssets/Unlocks/Reveals/O.Stars.png"),
    O_Stripes: require("../assets/AppAssets/Unlocks/Reveals/O.Stripes.png"),
    O_Waves: require("../assets/AppAssets/Unlocks/Reveals/O.Waves.png"),
    P_Dots: require("../assets/AppAssets/Unlocks/Reveals/P.Dots.png"),
    P_Flowers: require("../assets/AppAssets/Unlocks/Reveals/P.Flowers.png"),
    P_Hearts: require("../assets/AppAssets/Unlocks/Reveals/P.Hearts.png"),
    P_Stars: require("../assets/AppAssets/Unlocks/Reveals/P.Stars.png"),
    P_Stripes: require("../assets/AppAssets/Unlocks/Reveals/P.Stripes.png"),
    P_Waves: require("../assets/AppAssets/Unlocks/Reveals/P.Waves.png"),
    Pi_Dots: require("../assets/AppAssets/Unlocks/Reveals/Pi.Dots.png"),
    Pi_Flowers: require("../assets/AppAssets/Unlocks/Reveals/Pi.Flowers.png"),
    Pi_Hearts: require("../assets/AppAssets/Unlocks/Reveals/Pi.Hearts.png"),
    Pi_Stars: require("../assets/AppAssets/Unlocks/Reveals/Pi.Stars.png"),
    Pi_Stripes: require("../assets/AppAssets/Unlocks/Reveals/Pi.Stripes.png"),
    Pi_Waves: require("../assets/AppAssets/Unlocks/Reveals/Pi.Waves.png"),
    R_Dots: require("../assets/AppAssets/Unlocks/Reveals/R.Dots.png"),
    R_Flowers: require("../assets/AppAssets/Unlocks/Reveals/R.Flowers.png"),
    R_Hearts: require("../assets/AppAssets/Unlocks/Reveals/R.Hearts.png"),
    R_Stars: require("../assets/AppAssets/Unlocks/Reveals/R.Stars.png"),
    R_Stripes: require("../assets/AppAssets/Unlocks/Reveals/R.Stripes.png"),
    R_Waves: require("../assets/AppAssets/Unlocks/Reveals/R.Waves.png"),
    Spring_Summer: require("../assets/AppAssets/Unlocks/Reveals/Spring_Summer.png"),
    Tent_B: require("../assets/AppAssets/Unlocks/Reveals/Tent.B.png"),
    Tent_Bl: require("../assets/AppAssets/Unlocks/Reveals/Tent.Bl.png"),
    Tent_Br: require("../assets/AppAssets/Unlocks/Reveals/Tent.Br.png"),
    Tent_G: require("../assets/AppAssets/Unlocks/Reveals/Tent.G.png"),
    Tent_Gr: require("../assets/AppAssets/Unlocks/Reveals/Tent.Gr.png"),
    Tent_L: require("../assets/AppAssets/Unlocks/Reveals/Tent.L.png"),
    Tent_O: require("../assets/AppAssets/Unlocks/Reveals/Tent.O.png"),
    Tent_P: require("../assets/AppAssets/Unlocks/Reveals/Tent.P.png"),
    Tent_Pi: require("../assets/AppAssets/Unlocks/Reveals/Tent.Pi.png"),
    Tent_R: require("../assets/AppAssets/Unlocks/Reveals/Tent.R.png"),
    Tent_W: require("../assets/AppAssets/Unlocks/Reveals/Tent.W.png"),
    Tent_Y: require("../assets/AppAssets/Unlocks/Reveals/Tent.Y.png"),
    W_Dots: require("../assets/AppAssets/Unlocks/Reveals/W.Dots.png"),
    W_Flowers: require("../assets/AppAssets/Unlocks/Reveals/W.Flowers.png"),
    W_Hearts: require("../assets/AppAssets/Unlocks/Reveals/W.Hearts.png"),
    W_Stars: require("../assets/AppAssets/Unlocks/Reveals/W.Stars.png"),
    W_Stripes: require("../assets/AppAssets/Unlocks/Reveals/W.Stripes.png"),
    W_Waves: require("../assets/AppAssets/Unlocks/Reveals/W.Waves.png"),
    Y_Dots: require("../assets/AppAssets/Unlocks/Reveals/Y.Dots.png"),
    Y_Flowers: require("../assets/AppAssets/Unlocks/Reveals/Y.Flowers.png"),
    Y_Hearts: require("../assets/AppAssets/Unlocks/Reveals/Y.Hearts.png"),
    Y_Stars: require("../assets/AppAssets/Unlocks/Reveals/Y.Stars.png"),
    Y_Stripes: require("../assets/AppAssets/Unlocks/Reveals/Y.Stripes.png"),
    Y_Waves: require("../assets/AppAssets/Unlocks/Reveals/Y.Waves.png"),
  },
  silhouettes: {
    BaseballCap: require("../assets/AppAssets/Unlocks/Silhouettes/BaseballCap.png"),
    Beanie: require("../assets/AppAssets/Unlocks/Silhouettes/Beanie.png"),
    Beret: require("../assets/AppAssets/Unlocks/Silhouettes/Beret.png"),
    Bucket: require("../assets/AppAssets/Unlocks/Silhouettes/Bucket.png"),
    BucketHat: require("../assets/AppAssets/Unlocks/Silhouettes/BucketHat.png"),
    CatEars: require("../assets/AppAssets/Unlocks/Silhouettes/CatEars.png"),
    Cowboy: require("../assets/AppAssets/Unlocks/Silhouettes/Cowboy.png"),
    Crown: require("../assets/AppAssets/Unlocks/Silhouettes/Crown.png"),
    Duck: require("../assets/AppAssets/Unlocks/Silhouettes/Duck.png"),
    Egg: require("../assets/AppAssets/Unlocks/Silhouettes/Egg.png"),
    FlowerCrown: require("../assets/AppAssets/Unlocks/Silhouettes/FlowerCrown.png"),
    Headphones: require("../assets/AppAssets/Unlocks/Silhouettes/Headphones.png"),
    Leaf: require("../assets/AppAssets/Unlocks/Silhouettes/Leaf.png"),
    Pan: require("../assets/AppAssets/Unlocks/Silhouettes/Pan.png"),
    Paper: require("../assets/AppAssets/Unlocks/Silhouettes/Paper.png"),
    Party: require("../assets/AppAssets/Unlocks/Silhouettes/Party.png"),
    Patterns: require("../assets/AppAssets/Unlocks/Silhouettes/Patterns.png"),
    Propeller: require("../assets/AppAssets/Unlocks/Silhouettes/Propeller.png"),
    Raccoon: require("../assets/AppAssets/Unlocks/Silhouettes/Raccoon.png"),
    RussianHat: require("../assets/AppAssets/Unlocks/Silhouettes/RussianHat.png"),
    Seasons: require("../assets/AppAssets/Unlocks/Silhouettes/Seasons.png"),
    Skies: require("../assets/AppAssets/Unlocks/Silhouettes/Skies.png"),
    TentColor: require("../assets/AppAssets/Unlocks/Silhouettes/TentColor.png"),
    TopHat: require("../assets/AppAssets/Unlocks/Silhouettes/TopHat.png"),
  },
  armorSwatches: {
    Armor_B: {
      id: "blue",
      title: "Blue" ,
      key: "b",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Armor.B.png"),
    },
    Armor_Bl: {
      id: "black",
      title:"Black" ,
      key:"bl" ,
      asset: require("../assets/AppAssets/Unlocks/Reveals/Armor.Bl.png"),
    },
    Armor_Br: {
      id:"brown" ,
      title:"Brown" ,
      key: "br",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Armor.Br.png"),
    },
    Armor_G: {
      id: "green",
      title:"Green" ,
      key: "g",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Armor.G.png"),
    },
    Armor_Gr: {
      id: "gray",
      title: "Gray",
      key: "gr",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Armor.Gr.png"),
    },
    Armor_L: {
      id: "lightblue",
      title: "Light Blue",
      key: "l",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Armor.L.png"),
    },
    Armor_O: {
      id:"orange" ,
      title: "Orange",
      key: "o",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Armor.O.png"),
    },
    Armor_P: {
      id: "purple",
      title: "Purple",
      key: "p",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Armor.P.png"),
    },
    Armor_Pi: {
      id: "pink",
      title: "Pink",
      key: "pi",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Armor.Pi.png"),
    },
    Armor_R: {
      id: "red",
      title: "Red",
      key: "r",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Armor.R.png"),
    }, 
    Armor_Y: {
      id: "yellow",
      title: "Yellow",
      key: "y",
      asset: require("../assets/AppAssets/Unlocks/Reveals/Armor.Y.png"),
    }
  },
}
